export const reactRepo = {
  id: 10,
  name: 'react',
  fullName: 'facebook/react',
  githubId: '11111111',
  installationId: null,
  author: 'thozh',
  repoImg: 'https://avatars3.githubusercontent.com/u/69631?v=4',
  createdAt: '2020-07-10T09:25:50.000Z',
  dependenciesUpdatedAt: '2020-07-10T09:26:13.000Z',
  repoUrl: 'https://github.com/facebook/react',
  packageJson: {
    private: true,
    version: '16.6.1',
    workspaces: ['packages/*'],
    devDependencies: {
      art: '^0.10.1',
      'babel-cli': '^6.6.5',
      'babel-code-frame': '^6.26.0',
      'babel-core': '^6.0.0',
      'babel-eslint': '^10.0.0',
      'babel-jest': '^23.0.1',
      'babel-plugin-check-es2015-constants': '^6.5.0',
      'babel-plugin-external-helpers': '^6.22.0',
      'babel-plugin-syntax-trailing-function-commas': '^6.5.0',
      'babel-plugin-transform-async-to-generator': '^6.22.0',
      'babel-plugin-transform-class-properties': '^6.11.5',
      'babel-plugin-transform-es2015-arrow-functions': '^6.5.2',
      'babel-plugin-transform-es2015-block-scoped-functions': '^6.5.0',
      'babel-plugin-transform-es2015-block-scoping': '^6.23.0',
      'babel-plugin-transform-es2015-classes': '^6.5.2',
      'babel-plugin-transform-es2015-computed-properties': '^6.5.2',
      'babel-plugin-transform-es2015-destructuring': '^6.5.0',
      'babel-plugin-transform-es2015-for-of': '^6.5.2',
      'babel-plugin-transform-es2015-literals': '^6.5.0',
      'babel-plugin-transform-es2015-modules-commonjs': '^6.5.2',
      'babel-plugin-transform-es2015-object-super': '^6.5.0',
      'babel-plugin-transform-es2015-parameters': '^6.5.0',
      'babel-plugin-transform-es2015-shorthand-properties': '^6.5.0',
      'babel-plugin-transform-es2015-spread': '^6.5.2',
      'babel-plugin-transform-es2015-template-literals': '^6.5.2',
      'babel-plugin-transform-object-rest-spread': '^6.6.5',
      'babel-plugin-transform-react-jsx-source': '^6.8.0',
      'babel-plugin-transform-regenerator': '^6.26.0',
      'babel-preset-react': '^6.5.0',
      'babel-traverse': '^6.9.0',
      babylon: '6.18.0',
      chalk: '^1.1.3',
      'cli-table': '^0.3.1',
      'coffee-script': '^1.8.0',
      'core-js': '^2.2.1',
      coveralls: '^2.11.6',
      'create-react-class': '^15.6.3',
      'cross-env': '^5.1.1',
      danger: '^3.0.4',
      'error-stack-parser': '^2.0.2',
      eslint: '^4.1.0',
      'eslint-config-fbjs': '^1.1.1',
      'eslint-plugin-babel': '^3.3.0',
      'eslint-plugin-flowtype': '^2.25.0',
      'eslint-plugin-jest': '^21.6.1',
      'eslint-plugin-no-for-of-loops': '^1.0.0',
      'eslint-plugin-react': '^6.7.1',
      'eslint-plugin-react-internal': 'link:./scripts/eslint-rules/',
      'fbjs-scripts': '^0.8.3',
      filesize: '^3.5.6',
      'flow-bin': '^0.72.0',
      glob: '^6.0.4',
      'glob-stream': '^6.1.0',
      'google-closure-compiler': '20190106.0.0',
      'gzip-size': '^3.0.0',
      'jasmine-check': '^1.0.0-rc.0',
      jest: '^23.1.0',
      'jest-diff': '^23.0.1',
      minimatch: '^3.0.4',
      minimist: '^1.2.0',
      mkdirp: '^0.5.1',
      ncp: '^2.0.0',
      'object-assign': '^4.1.1',
      prettier: '1.13.7',
      'prop-types': '^15.6.2',
      'random-seed': '^0.3.0',
      'react-lifecycles-compat': '^3.0.2',
      rimraf: '^2.6.1',
      rollup: '^0.52.1',
      'rollup-plugin-babel': '^3.0.1',
      'rollup-plugin-commonjs': '^8.2.6',
      'rollup-plugin-node-resolve': '^2.1.1',
      'rollup-plugin-prettier': '^0.3.0',
      'rollup-plugin-replace': '^2.0.0',
      'rollup-plugin-strip-banner': '^0.2.0',
      semver: '^5.5.0',
      targz: '^1.0.1',
      through2: '^2.0.0',
      tmp: '~0.0.28',
      typescript: '~1.8.10',
      '@mattiasbuelens/web-streams-polyfill': '0.1.0',
    },
    devEngines: {
      node: '8.x || 9.x || 10.x || 11.x',
    },
    jest: {
      testRegex: '/scripts/jest/dont-run-jest-directly\\.js$',
    },
    scripts: {
      build: 'node ./scripts/rollup/build.js',
      linc: 'node ./scripts/tasks/linc.js',
      lint: 'node ./scripts/tasks/eslint.js',
      'lint-build': 'node ./scripts/rollup/validate/index.js',
      postinstall:
        'node node_modules/fbjs-scripts/node/check-dev-engines.js package.json && node ./scripts/flow/createFlowConfigs.js',
      'debug-test':
        'cross-env NODE_ENV=development node --inspect-brk node_modules/.bin/jest --config ./scripts/jest/config.source.js --runInBand',
      test:
        'cross-env NODE_ENV=development jest --config ./scripts/jest/config.source.js',
      'test-fire':
        'cross-env NODE_ENV=development jest --config ./scripts/jest/config.source-fire.js',
      'test-prod':
        'cross-env NODE_ENV=production jest --config ./scripts/jest/config.source.js',
      'test-fire-prod':
        'cross-env NODE_ENV=production jest --config ./scripts/jest/config.source-fire.js',
      'test-prod-build': 'yarn test-build-prod',
      'test-build':
        'cross-env NODE_ENV=development jest --config ./scripts/jest/config.build.js',
      'test-build-prod':
        'cross-env NODE_ENV=production jest --config ./scripts/jest/config.build.js',
      flow: 'node ./scripts/tasks/flow.js',
      'flow-ci': 'node ./scripts/tasks/flow-ci.js',
      prettier: 'node ./scripts/prettier/index.js write-changed',
      'prettier-all': 'node ./scripts/prettier/index.js write',
      'version-check': 'node ./scripts/tasks/version-check.js',
    },
  },
  dependencies: {
    deps: [
      [
        '@mattiasbuelens/web-streams-polyfill',
        '0.1.0',
        '0.1.0',
        '0.3.2',
        '',
        'devDependencies',
        'https://github.com/MattiasBuelens/web-streams-polyfill#readme',
      ],
      [
        'art',
        '0.10.1',
        '0.10.3',
        '0.10.3',
        '',
        'devDependencies',
        'http://sebmarkbage.github.io/art',
      ],
      [
        'babel-core',
        '6.26.0',
        '6.26.3',
        '6.26.3',
        '',
        'devDependencies',
        'https://babeljs.io/',
      ],
      [
        'babel-eslint',
        '10.0.0',
        '10.1.0',
        '10.1.0',
        '',
        'devDependencies',
        'https://github.com/babel/babel-eslint',
      ],
      [
        'babel-jest',
        '23.0.1',
        '23.6.0',
        '26.1.0',
        '',
        'devDependencies',
        'https://github.com/facebook/jest#readme',
      ],
      [
        'babel-plugin-transform-es2015-modules-commonjs',
        '6.26.0',
        '6.26.2',
        '6.26.2',
        '',
        'devDependencies',
        'https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-es2015-modules-commonjs',
      ],
      [
        'chalk',
        '1.1.3',
        '1.1.3',
        '4.1.0',
        '',
        'devDependencies',
        'https://github.com/chalk/chalk#readme',
      ],
      [
        'coffee-script',
        '1.12.5',
        '1.12.7',
        '1.12.7',
        '',
        'devDependencies',
        'http://coffeescript.org',
      ],
      [
        'core-js',
        '2.5.5',
        '2.6.11',
        '3.6.5',
        '',
        'devDependencies',
        'https://github.com/zloirock/core-js#readme',
      ],
      [
        'coveralls',
        '2.13.1',
        '2.13.3',
        '3.1.0',
        '',
        'devDependencies',
        'https://github.com/nickmerwin/node-coveralls#readme',
      ],
      [
        'cross-env',
        '5.1.1',
        '5.2.1',
        '7.0.2',
        '',
        'devDependencies',
        'https://github.com/kentcdodds/cross-env#readme',
      ],
      [
        'danger',
        '3.0.4',
        '3.9.0',
        '10.2.1',
        '',
        'devDependencies',
        'https://github.com/danger/danger-js#readme',
      ],
      [
        'error-stack-parser',
        '2.0.2',
        '2.0.6',
        '2.0.6',
        '',
        'devDependencies',
        'https://www.stacktracejs.com',
      ],
      [
        'eslint',
        '4.15.0',
        '4.19.1',
        '7.4.0',
        '',
        'devDependencies',
        'https://eslint.org',
      ],
      [
        'eslint-config-fbjs',
        '1.1.1',
        '1.1.1',
        '3.1.1',
        '',
        'devDependencies',
        'https://github.com/facebook/fbjs#readme',
      ],
      [
        'eslint-plugin-babel',
        '3.3.0',
        '3.3.0',
        '5.3.1',
        '',
        'devDependencies',
        'https://github.com/babel/eslint-plugin-babel#readme',
      ],
      [
        'eslint-plugin-flowtype',
        '2.32.1',
        '2.50.3',
        '5.2.0',
        '',
        'devDependencies',
        'https://github.com/gajus/eslint-plugin-flowtype#readme',
      ],
      [
        'eslint-plugin-jest',
        '21.6.1',
        '21.27.2',
        '23.18.0',
        '',
        'devDependencies',
        'https://github.com/jest-community/eslint-plugin-jest#readme',
      ],
      [
        'eslint-plugin-no-for-of-loops',
        '1.0.0',
        '1.0.1',
        '1.0.1',
        '',
        'devDependencies',
        'https://github.com/dharFr/eslint-plugin-no-for-of-loops#readme',
      ],
      [
        'eslint-plugin-react',
        '6.10.3',
        '6.10.3',
        '7.20.3',
        '',
        'devDependencies',
        'https://github.com/yannickcr/eslint-plugin-react',
      ],
      [
        'eslint-plugin-react-internal',
        '0.0.0',
        'exotic',
        'exotic',
        '',
        'devDependencies',
        'link:./scripts/eslint-rules',
      ],
      [
        'fbjs-scripts',
        '0.8.3',
        '0.8.3',
        '1.2.0',
        '',
        'devDependencies',
        'https://github.com/facebook/fbjs#readme',
      ],
      [
        'filesize',
        '3.5.6',
        '3.6.1',
        '6.1.0',
        '',
        'devDependencies',
        'https://filesizejs.com',
      ],
      [
        'flow-bin',
        '0.72.0',
        '0.72.0',
        '0.129.0',
        '',
        'devDependencies',
        'https://github.com/flowtype/flow-bin#readme',
      ],
      [
        'glob',
        '6.0.4',
        '6.0.4',
        '7.1.6',
        '',
        'devDependencies',
        'https://github.com/isaacs/node-glob#readme',
      ],
      [
        'google-closure-compiler',
        '20190106.0.0',
        '20190106.0.0',
        '20200628.0.0',
        '',
        'devDependencies',
        'https://developers.google.com/closure/compiler/',
      ],
      [
        'gzip-size',
        '3.0.0',
        '3.0.0',
        '5.1.1',
        '',
        'devDependencies',
        'https://github.com/sindresorhus/gzip-size#readme',
      ],
      [
        'jest',
        '23.1.0',
        '23.6.0',
        '26.1.0',
        '',
        'devDependencies',
        'https://jestjs.io/',
      ],
      [
        'jest-diff',
        '23.0.1',
        '23.6.0',
        '26.1.0',
        '',
        'devDependencies',
        'https://github.com/facebook/jest#readme',
      ],
      [
        'minimist',
        '1.2.0',
        '1.2.5',
        '1.2.5',
        '',
        'devDependencies',
        'https://github.com/substack/minimist',
      ],
      [
        'mkdirp',
        '0.5.1',
        '0.5.5',
        '1.0.4',
        '',
        'devDependencies',
        'https://github.com/isaacs/node-mkdirp#readme',
      ],
      [
        'prettier',
        '1.13.7',
        '1.13.7',
        '2.0.5',
        '',
        'devDependencies',
        'https://prettier.io',
      ],
      [
        'prop-types',
        '15.6.2',
        '15.7.2',
        '15.7.2',
        '',
        'devDependencies',
        'https://facebook.github.io/react/',
      ],
      [
        'react-lifecycles-compat',
        '3.0.2',
        '3.0.4',
        '3.0.4',
        '',
        'devDependencies',
        'https://github.com/reactjs/react-lifecycles-compat#readme',
      ],
      [
        'rimraf',
        '2.6.2',
        '2.7.1',
        '3.0.2',
        '',
        'devDependencies',
        'https://github.com/isaacs/rimraf#readme',
      ],
      [
        'rollup',
        '0.52.1',
        '0.52.3',
        '2.21.0',
        '',
        'devDependencies',
        'https://rollupjs.org/',
      ],
      [
        'rollup-plugin-babel',
        '3.0.2',
        '3.0.7',
        '4.4.0',
        '',
        'devDependencies',
        'https://github.com/rollup/rollup-plugin-babel',
      ],
      [
        'rollup-plugin-commonjs',
        '8.2.6',
        '8.4.1',
        '10.1.0',
        '',
        'devDependencies',
        'https://github.com/rollup/rollup-plugin-commonjs',
      ],
      [
        'rollup-plugin-node-resolve',
        '2.1.1',
        '2.1.1',
        '5.2.0',
        '',
        'devDependencies',
        'https://github.com/rollup/rollup-plugin-node-resolve#readme',
      ],
      [
        'rollup-plugin-prettier',
        '0.3.0',
        '0.3.0',
        '2.1.0',
        '',
        'devDependencies',
        'https://github.com/mjeanroy/rollup-plugin-prettier#readme',
      ],
      [
        'rollup-plugin-replace',
        '2.0.0',
        '2.2.0',
        '2.2.0',
        '',
        'devDependencies',
        'https://github.com/rollup/rollup-plugin-replace#readme',
      ],
      [
        'rollup-plugin-strip-banner',
        '0.2.0',
        '0.2.0',
        '2.0.0',
        '',
        'devDependencies',
        'https://github.com/mjeanroy/rollup-plugin-strip-banner#readme',
      ],
      [
        'semver',
        '5.5.0',
        '5.7.1',
        '7.3.2',
        '',
        'devDependencies',
        'https://github.com/npm/node-semver#readme',
      ],
      [
        'through2',
        '2.0.3',
        '2.0.5',
        '4.0.2',
        '',
        'devDependencies',
        'https://github.com/rvagg/through2#readme',
      ],
      [
        'tmp',
        '0.0.33',
        '0.0.33',
        '0.2.1',
        '',
        'devDependencies',
        'http://github.com/raszi/node-tmp',
      ],
      [
        'typescript',
        '1.8.10',
        '1.8.10',
        '3.9.6',
        '',
        'devDependencies',
        'https://www.typescriptlang.org/',
      ],
    ],
  },
  branch: '16.8.6',
  path: '/',
  isConfigured: true,
  score: 43,
  framework: null,
  hasYarnLock: true,
  crawlError: '',
  users: [
    {
      id: 17,
      username: 'thozh',
      githubId: '37123351',
      githubToken: '97cb936d5808c3ebf32c782a1a23be0703b3e806',
      avatarUrl: 'https://avatars2.githubusercontent.com/u/37123351?v=4',
      validated: true,
    },
  ],
}
